/* ═══════════════════════════════════════════════════════
   COURSE DATA — 30-Day Node.js Mastery Plan
   To add a new course: create a new file in this directory
   following the same COURSE_DATA structure, then register
   it in js/config.js inside initStorage().
═══════════════════════════════════════════════════════ */
const NODEJS_30DAY_COURSE={
  id:"nodejs-30day",
  title:"30-Day Node.js Mastery Plan",
  subtitle:"Frontend → Fullstack · Backend Blueprint",
  description:"Tailored for a frontend engineer with 5+ years of experience. This plan takes you from zero to confident backend developer — covering Node.js fundamentals, REST APIs, databases, authentication, and real-world architecture patterns.",
  duration:"30 Days",dailyEffort:"2–3 Hours",prerequisites:"JavaScript ES6+",
  outcome:"REST API + Portfolio Project",
  category:"Backend Development",level:"Intermediate",
  image:"assets/og/courses/nodejs-card.svg",
  weeks:[
    {id:1,label:"Week 1",title:"Foundations — How Node.js Really Works",color:"#7c4dff",colorSoft:"#ede7f6",days:[1,2,3,4,5,6,7]},
    {id:2,label:"Week 2",title:"APIs & Data Layer",color:"#007b83",colorSoft:"#e0f5f5",days:[8,9,10,11,12,13,14]},
    {id:3,label:"Week 3",title:"Auth, Security & Advanced Patterns",color:"#137333",colorSoft:"#e6f4ea",days:[15,16,17,18,19,20,21]},
    {id:4,label:"Week 4",title:"Capstone Project & Production",color:"#e37400",colorSoft:"#fef7e0",days:[22,23,24,25,26,27,28,29,30]}
  ],
  days:[
    {id:1,title:"Node.js Setup & The Mental Model",subtitle:"What is Node, V8, libuv · Installation · npm basics",tags:["Concept"],time:"~2 hrs",
     topics:["What is Node.js? Why non-blocking I/O?","V8 engine + libuv event loop overview","Install Node via nvm (Node Version Manager)","npm init, package.json structure","CommonJS (require/module.exports) vs ESModules (import/export)","Running first .js file with node"],
     resources:[{label:"Node.js Official Guides",url:"https://nodejs.org/en/docs/guides"},{label:"nvm on GitHub",url:"https://github.com/nvm-sh/nvm"},{label:"Node.js Crash Course (Traversy)",url:"https://www.youtube.com/watch?v=ENrzD9HAZK4"},{label:"nodejs.dev — Learn Node",url:"https://nodejs.dev/en/learn/"}],
     goal:"Install Node, run a Hello World server, understand the difference between browser JS and Node.js."},
    {id:2,title:"The Event Loop — Deep Dive",subtitle:"Call stack · Web APIs · Callback queue · Microtasks",tags:["Concept"],time:"~2.5 hrs",
     topics:["Call stack, heap, event loop phases","setTimeout vs setImmediate vs process.nextTick","Microtask queue (Promise callbacks)","Why blocking the event loop is bad","Async patterns: Callbacks → Promises → async/await"],
     resources:[{label:"What the heck is the event loop? (JSConf)",url:"https://www.youtube.com/watch?v=8aGhZQkoFbQ"},{label:"Node.js Event Loop — Official Docs",url:"https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick"},{label:"LogRocket: Complete Event Loop Guide",url:"https://blog.logrocket.com/a-complete-guide-to-the-node-js-event-loop/"}],
     goal:"Explain to yourself (rubber-duck test) what happens when a setTimeout callback runs. Write 3 async snippets using callbacks, promises, and async/await."},
    {id:3,title:"Core Modules — fs, path, os, http",subtitle:"Built-in modules · Reading files · Raw HTTP server",tags:["Practice"],time:"~2.5 hrs",
     topics:["fs module — readFile, writeFile, createReadStream","path module — join, resolve, extname","os module — platform, cpus, freemem","http.createServer() — req/res lifecycle","Manual routing with req.url & req.method","Buffer & Streams introduction"],
     resources:[{label:"Node.js fs module docs",url:"https://nodejs.org/api/fs.html"},{label:"Node.js http module docs",url:"https://nodejs.org/api/http.html"},{label:"FreeCodeCamp — Streams Guide",url:"https://www.freecodecamp.org/news/node-js-streams-everything-you-need-to-know-c9141306be93/"}],
     goal:"Build a raw HTTP server (no frameworks) that reads a JSON file and returns it as a response."},
    {id:4,title:"npm, Modules & Project Structure",subtitle:"npm ecosystem · semantic versioning · folder architecture",tags:["Concept"],time:"~2 hrs",
     topics:["npm install --save vs --save-dev","package-lock.json and reproducible builds","SemVer (^1.2.3 vs ~1.2.3 vs exact)","Creating & publishing your own npm module","Folder structure: MVC pattern basics","Environment variables with dotenv"],
     resources:[{label:"npm Official Docs",url:"https://docs.npmjs.com/about-npm"},{label:"SemVer specification",url:"https://semver.org/"},{label:"dotenv package on GitHub",url:"https://github.com/motdotla/dotenv"}],
     goal:"Restructure yesterday's server into /src/routes, /src/controllers, /config folders. Add dotenv for port configuration."},
    {id:5,title:"Express.js — The Framework Layer",subtitle:"Routing · Middleware · Request & Response objects",tags:["Practice"],time:"~2.5 hrs",
     topics:["Installing Express, first server","Router, app.get/post/put/delete","Middleware: next(), order matters","express.json() and express.urlencoded()","Static files with express.static()","Error handling middleware (4 args)"],
     resources:[{label:"Express.js Official Docs",url:"https://expressjs.com/"},{label:"Express Routing Guide",url:"https://expressjs.com/en/guide/routing.html"},{label:"Express Middleware Guide",url:"https://expressjs.com/en/guide/using-middleware.html"}],
     goal:"Build an Express server with 5 routes. Add a custom logging middleware that prints method + URL + timestamp."},
    {id:6,title:"REST API Design Principles",subtitle:"HTTP verbs · Status codes · RESTful conventions",tags:["Concept"],time:"~2 hrs",
     topics:["REST constraints and principles","HTTP methods semantics (GET/POST/PUT/PATCH/DELETE)","Status codes: 2xx, 4xx, 5xx","URL design: /users/:id/posts vs /getUserPosts","JSON response structure best practices","Versioning: /api/v1/"],
     resources:[{label:"RESTful API Design — Microsoft",url:"https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design"},{label:"HTTP Status Codes Reference",url:"https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"}],
     goal:"Design (on paper or in Postman) a complete REST API for a Blog system with users, posts, comments."},
    {id:7,title:"Week 1 Mini-Project — Notes API",subtitle:"CRUD · In-memory storage · Postman testing",tags:["Project"],time:"~3 hrs",
     topics:["Build a full CRUD Notes API","In-memory array as data store","Request body parsing & validation","Postman collection creation","Testing all routes: GET, POST, PUT, DELETE","Adding timestamps and IDs"],
     resources:[{label:"Postman Learning Center",url:"https://learning.postman.com/"},{label:"Thunder Client for VS Code",url:"https://www.thunderclient.com/"}],
     goal:"Ship a working Notes API with full CRUD. Every route tested in Postman with passing assertions."},
    {id:8,title:"MongoDB & Mongoose — NoSQL Foundations",subtitle:"Documents · Collections · Schema design",tags:["Concept"],time:"~3 hrs",
     topics:["MongoDB Atlas free cluster setup","Documents vs SQL rows — mental model shift","Mongoose connect, Schema, Model","CRUD with Mongoose: find, save, findByIdAndUpdate","Schema types, required, default, validators","MongoDB Compass GUI overview"],
     resources:[{label:"MongoDB Atlas",url:"https://www.mongodb.com/atlas"},{label:"Mongoose Official Docs",url:"https://mongoosejs.com/docs/"},{label:"MongoDB University (Free)",url:"https://learn.mongodb.com/"}],
     goal:"Connect your Notes API to MongoDB Atlas. Replace in-memory array with Mongoose. All 7 CRUD routes working with real database."},
    {id:9,title:"Advanced Mongoose — Queries & Aggregation",subtitle:"Filtering · Pagination · Population · Aggregation",tags:["Practice"],time:"~2.5 hrs",
     topics:["Chaining Mongoose queries","Filtering: find({price: {$gt: 100}})","Pagination with skip() and limit()","Sorting with sort()","populate() for virtual joins","MongoDB aggregation pipeline basics"],
     resources:[{label:"Mongoose Queries Docs",url:"https://mongoosejs.com/docs/queries.html"},{label:"Mongoose Populate Docs",url:"https://mongoosejs.com/docs/populate.html"},{label:"MongoDB Aggregation Docs",url:"https://www.mongodb.com/docs/manual/aggregation/"}],
     goal:"Add filtering (?search=term), pagination (?page=1&limit=10), and sorting (?sort=createdAt) to your Notes API."},
    {id:10,title:"Input Validation & Error Handling",subtitle:"Joi / Zod · Custom middleware · Centralized errors",tags:["Practice"],time:"~2.5 hrs",
     topics:["Why validation matters at the API layer","Joi or Zod for schema validation","Custom AppError class with status codes","Async error wrapper (catchAsync pattern)","Global error handler middleware","Mongoose validation errors — handling them properly"],
     resources:[{label:"Joi API Documentation",url:"https://joi.dev/api/"},{label:"Zod Documentation",url:"https://zod.dev/"},{label:"Jonas Schmedtmann — Node Bootcamp",url:"https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/"}],
     goal:"Add Joi validation to POST/PUT routes and a global error middleware that catches all unhandled errors."},
    {id:11,title:"SQL Databases — PostgreSQL with Sequelize",subtitle:"Relational model · ORM · Migrations",tags:["Concept"],time:"~3 hrs",
     topics:["PostgreSQL installation and psql CLI","Relational concepts: tables, foreign keys, joins","Sequelize setup & connection","Defining Models, sync vs migrations","hasOne, hasMany, belongsTo associations","Raw queries vs ORM queries"],
     resources:[{label:"Sequelize v6 Official Docs",url:"https://sequelize.org/docs/v6/"},{label:"PostgreSQL Tutorial",url:"https://www.postgresql.org/docs/current/tutorial.html"},{label:"Railway.app — Free PostgreSQL hosting",url:"https://railway.app/"}],
     goal:"Rebuild the Notes API using PostgreSQL + Sequelize. Compare the experience with MongoDB."},
    {id:12,title:"Advanced SQL — Joins, Transactions & Indexes",subtitle:"JOIN types · ACID · Query performance",tags:["Advanced"],time:"~3 hrs",
     topics:["INNER, LEFT, RIGHT, FULL OUTER joins","GROUP BY, HAVING, subqueries","Transactions and ACID properties","BEGIN, COMMIT, ROLLBACK in Sequelize","Indexes: B-tree, composite, partial","EXPLAIN ANALYZE for query optimization"],
     resources:[{label:"PostgreSQL Joins Explained",url:"https://www.postgresqltutorial.com/postgresql-joins/"},{label:"PostgreSQL Transactions",url:"https://www.postgresql.org/docs/current/tutorial-transactions.html"}],
     goal:"Write complex JOIN queries for your Notes app. Add a transaction that creates a user and their first note atomically."},
    {id:13,title:"Redis — Caching Layer",subtitle:"In-memory store · Cache patterns · Sessions",tags:["Advanced"],time:"~2.5 hrs",
     topics:["What is Redis and why use it?","ioredis vs node-redis client","SET, GET, EXPIRE, DEL operations","Cache-aside pattern implementation","Redis for session storage","Rate limiting with Redis counters"],
     resources:[{label:"Redis Official Docs",url:"https://redis.io/docs/"},{label:"ioredis on GitHub",url:"https://github.com/luin/ioredis"},{label:"Redis University (Free)",url:"https://university.redis.com/"}],
     goal:"Add Redis caching to your Notes list endpoint. First request hits DB, subsequent requests serve from cache."},
    {id:14,title:"Week 2 Project — Blog API with Real Database",subtitle:"Complete RESTful API · MongoDB · Pagination",tags:["Project"],time:"~4 hrs",
     topics:["Blog API: users, posts, comments entities","Mongoose schemas with relationships","Full CRUD for posts & comments","Pagination and filtering on posts","User association (author field)","API documentation with Postman collection"],
     resources:[{label:"Postman API Documentation",url:"https://learning.postman.com/docs/publishing-your-api/documenting-your-api/"}],
     goal:"Ship a fully documented Blog API with users, posts, and comments. Postman collection with 15+ tests."},
    {id:15,title:"JWT Authentication — Theory & Implementation",subtitle:"Tokens · Signing · Verifying · Protecting routes",tags:["Concept"],time:"~3 hrs",
     topics:["What is JWT? Header.Payload.Signature","jsonwebtoken library: sign() and verify()","Access tokens vs Refresh tokens","Auth middleware: extracting bearer token","Protecting routes with authGuard","Storing JWTs: localStorage vs httpOnly cookie"],
     resources:[{label:"JWT.io — Debugger & Docs",url:"https://jwt.io/"},{label:"jsonwebtoken on npm",url:"https://www.npmjs.com/package/jsonwebtoken"},{label:"OWASP: JWT Security Cheatsheet",url:"https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html"}],
     goal:"Add JWT auth to Blog API. Implement register, login, and protect POST/PUT/DELETE routes."},
    {id:16,title:"Password Security — bcrypt & Best Practices",subtitle:"Hashing · Salting · Timing attacks",tags:["Practice"],time:"~2 hrs",
     topics:["Why never store plaintext passwords","bcrypt: saltRounds and hash()","bcrypt.compare() for login","Timing-safe comparison","Password strength validation","Mongoose pre-save hook for hashing"],
     resources:[{label:"bcrypt on npm",url:"https://www.npmjs.com/package/bcrypt"},{label:"OWASP Password Storage Cheatsheet",url:"https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html"}],
     goal:"Hash all passwords with bcrypt before storing. Implement a pre-save hook in Mongoose User model."},
    {id:17,title:"OAuth 2.0 & Social Login",subtitle:"Google OAuth · Passport.js · Strategies",tags:["Advanced"],time:"~3 hrs",
     topics:["OAuth 2.0 flow: Authorization Code Grant","Passport.js and strategies","passport-google-oauth20 setup","Callback URLs and state parameter","Linking social accounts to existing users","Session vs JWT in OAuth context"],
     resources:[{label:"Passport.js Docs",url:"http://www.passportjs.org/docs/"},{label:"Google OAuth 2.0 Guide",url:"https://developers.google.com/identity/protocols/oauth2"},{label:"passport-google-oauth20",url:"https://www.npmjs.com/package/passport-google-oauth20"}],
     goal:"Add Google OAuth login to your Blog API. User can sign in with Google and receive a JWT."},
    {id:18,title:"Role-Based Access Control (RBAC)",subtitle:"Roles · Permissions · Resource ownership",tags:["Advanced"],time:"~2.5 hrs",
     topics:["RBAC vs ABAC — when to use what","Role enum in User schema (user, admin, moderator)","Permission middleware factory","Resource ownership check (is this your post?)","Admin-only routes","Role hierarchy"],
     resources:[{label:"RBAC Tutorial",url:"https://auth0.com/docs/manage-users/access-control/rbac"},{label:"CASL — isomorphic authorization",url:"https://casl.js.org/v6/en/"}],
     goal:"Add admin role. Only admins can DELETE any post; users can only delete their own. Test with Postman."},
    {id:19,title:"File Uploads — Multer & Cloud Storage",subtitle:"multipart/form-data · Multer · AWS S3 / Cloudinary",tags:["Practice"],time:"~3 hrs",
     topics:["multipart/form-data basics","Multer: disk vs memory storage","File type validation and size limits","Cloudinary SDK for image uploads","Generating signed upload URLs","Deleting files when record deleted"],
     resources:[{label:"Multer on npm",url:"https://www.npmjs.com/package/multer"},{label:"Cloudinary Node.js SDK",url:"https://cloudinary.com/documentation/node_integration"},{label:"AWS S3 SDK v3",url:"https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/"}],
     goal:"Add avatar upload to user profile. Files stored on Cloudinary. Old file deleted when new one is uploaded."},
    {id:20,title:"Email & Notifications",subtitle:"Nodemailer · Email templates · Queues",tags:["Practice"],time:"~2.5 hrs",
     topics:["Nodemailer with Gmail/SendGrid/Resend","HTML email templates with handlebars","Email verification flow","Password reset with time-limited tokens","Bull queue for async email sending","Webhook handling (Stripe/SendGrid events)"],
     resources:[{label:"Nodemailer Docs",url:"https://nodemailer.com/about/"},{label:"Resend — Email API",url:"https://resend.com/"},{label:"Bull Queue on GitHub",url:"https://github.com/OptimalBits/bull"}],
     goal:"Implement email verification. After registration, user gets a verification link. Account activates on click."},
    {id:21,title:"Week 3 Project — Auth-Complete API",subtitle:"Registration · Login · RBAC · Email verification",tags:["Project"],time:"~4 hrs",
     topics:["Complete auth system: register, verify, login, logout","Forgot/reset password flow","Protected routes with RBAC","Profile update with avatar","Admin panel endpoints","API rate limiting"],
     resources:[{label:"express-rate-limit",url:"https://www.npmjs.com/package/express-rate-limit"}],
     goal:"Ship a production-ready auth system. All flows working: registration with email verification, login, password reset, profile update."},
    {id:22,title:"WebSockets & Real-time",subtitle:"Socket.io · Rooms · Events · Presence",tags:["Advanced"],time:"~3 hrs",
     topics:["HTTP long polling vs WebSockets","Socket.io server & client setup","Emitting and listening to events","Rooms and namespaces","Broadcasting to specific users","Presence indicators (who's online)"],
     resources:[{label:"Socket.io Official Docs",url:"https://socket.io/docs/v4/"},{label:"Socket.io with React Tutorial",url:"https://socket.io/how-to/use-with-react"}],
     goal:"Add real-time notifications to your blog. When someone comments on your post, you get a live notification."},
    {id:23,title:"Testing — Unit & Integration Tests",subtitle:"Jest · Supertest · Test databases",tags:["Practice"],time:"~3 hrs",
     topics:["Why testing matters for production code","Jest setup: describe, it, expect","Supertest for HTTP integration tests","Mocking with jest.fn() and jest.mock()","Test database strategy (separate DB per test)","Code coverage reports"],
     resources:[{label:"Jest Official Docs",url:"https://jestjs.io/docs/getting-started"},{label:"Supertest on GitHub",url:"https://github.com/visionmedia/supertest"},{label:"Testing Node.js Apps — Fireship",url:"https://www.youtube.com/watch?v=FKnzS_icp20"}],
     goal:"Write integration tests for all auth routes (register, login, protected route). Achieve 80%+ coverage."},
    {id:24,title:"API Documentation with Swagger",subtitle:"OpenAPI 3.0 · swagger-ui-express · JSDoc",tags:["Practice"],time:"~2 hrs",
     topics:["OpenAPI 3.0 specification format","swagger-jsdoc for auto-generation","swagger-ui-express for serving docs","Documenting request/response schemas","Authentication in Swagger UI","Versioning your API docs"],
     resources:[{label:"OpenAPI 3.0 Specification",url:"https://swagger.io/specification/"},{label:"swagger-ui-express on npm",url:"https://www.npmjs.com/package/swagger-ui-express"},{label:"swagger-jsdoc on npm",url:"https://www.npmjs.com/package/swagger-jsdoc"}],
     goal:"Document your entire Blog API with Swagger. Every endpoint should have request/response examples."},
    {id:25,title:"Performance Optimization",subtitle:"Profiling · Clustering · Compression · PM2",tags:["Advanced"],time:"~3 hrs",
     topics:["Node.js --inspect and Chrome DevTools profiling","Cluster module and worker processes","PM2 for process management","gzip compression with compression middleware","Database query optimization","Connection pooling"],
     resources:[{label:"Node.js Profiling Guide",url:"https://nodejs.org/en/docs/guides/simple-profiling"},{label:"PM2 Official Docs",url:"https://pm2.keymetrics.io/docs/"},{label:"Node.js Cluster Module",url:"https://nodejs.org/api/cluster.html"}],
     goal:"Profile your API under load with autocannon. Implement clustering and measure throughput improvement."},
    {id:26,title:"Security Hardening",subtitle:"Helmet · CORS · Rate limiting · OWASP Top 10",tags:["Advanced"],time:"~2.5 hrs",
     topics:["Helmet.js for security headers","CORS configuration and origins","SQL/NoSQL injection prevention","XSS protection and sanitization","CSRF tokens","Security audit with npm audit"],
     resources:[{label:"Helmet.js Docs",url:"https://helmetjs.github.io/"},{label:"OWASP Top 10 Node.js",url:"https://owasp.org/www-project-nodejs-goat/"},{label:"express-mongo-sanitize",url:"https://www.npmjs.com/package/express-mongo-sanitize"}],
     goal:"Run npm audit on your project. Add Helmet, CORS config, rate limiting, and sanitize all user inputs."},
    {id:27,title:"Deployment — Docker & Containers",subtitle:"Dockerfile · docker-compose · Environment configs",tags:["Advanced"],time:"~3 hrs",
     topics:["Docker fundamentals: images, containers, layers","Writing an optimized Dockerfile for Node","Multi-stage builds","docker-compose for local dev stack (app + DB + Redis)","Environment variables in Docker","Health checks"],
     resources:[{label:"Docker Official Docs",url:"https://docs.docker.com/"},{label:"Docker for Node.js",url:"https://nodejs.org/en/docs/guides/nodejs-docker-webapp"},{label:"Docker Compose Getting Started",url:"https://docs.docker.com/compose/gettingstarted/"}],
     goal:"Containerize your Blog API. docker-compose up should start app, MongoDB, and Redis with one command."},
    {id:28,title:"CI/CD with GitHub Actions",subtitle:"Automated testing · Docker builds · Deployments",tags:["Advanced"],time:"~2.5 hrs",
     topics:["GitHub Actions: workflows, jobs, steps","Running tests on every PR","Building and pushing Docker images","Deploying to Railway/Render/Fly.io","Environment secrets management","Rollback strategies"],
     resources:[{label:"GitHub Actions Docs",url:"https://docs.github.com/en/actions"},{label:"Render.com Deployment",url:"https://render.com/"},{label:"Railway.app Deployment",url:"https://railway.app/"}],
     goal:"Set up a pipeline: push to main → tests run → Docker image builds → auto-deploys to your hosting provider."},
    {id:29,title:"Microservices Introduction",subtitle:"Service decomposition · API Gateway · Message queues",tags:["Advanced"],time:"~3 hrs",
     topics:["Monolith vs Microservices tradeoffs","Domain-driven design basics","HTTP vs event-driven communication","RabbitMQ / Kafka introduction","API Gateway pattern with express-gateway","Service discovery concepts"],
     resources:[{label:"Microservices.io Patterns",url:"https://microservices.io/patterns/"},{label:"RabbitMQ Tutorials",url:"https://www.rabbitmq.com/getstarted.html"},{label:"Martin Fowler — Microservices",url:"https://martinfowler.com/articles/microservices.html"}],
     goal:"Split your Blog API into 2 microservices: User Service and Post Service. Communicate via HTTP and one RabbitMQ event."},
    {id:30,title:"Capstone Project — Production-Ready API",subtitle:"Everything combined · Ship it · Write the README",tags:["Project"],time:"~6 hrs",
     topics:["Complete auth + CRUD + RBAC + file uploads","Redis caching on expensive queries","WebSocket for real-time notifications","Tests with 80%+ coverage","Swagger documentation","Deployed to production with CI/CD","README with architecture diagram"],
     resources:[{label:"Awesome Node.js — curated list",url:"https://github.com/sindresorhus/awesome-nodejs"},{label:"Production Checklist",url:"https://goldbergyoni.com/checklist-best-practice-of-node-js-in-production/"}],
     goal:"Ship your capstone project to production. Share the GitHub repo + live URL. You are now a backend developer."}
  ]
};
